### ISSUE TITLE
[Bug]: Incorrect Architecture

### ISSUE THREAD

**Issue by UnownPlain** [russellbanks/Komac#1036]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

`komac update Zen-Team.Zen-Browser --version 1.7.2b --urls https://github.com/zen-browser/desktop/releases/download/1.7.2b/zen.installer.exe https://github.com/zen-browser/desktop/releases/download/1.7.2b/zen.installer-arm64.exe`

x64 installer is incorrectly detected as a x86 installer. (https://github.com/microsoft/winget-pkgs/pull/212709#pullrequestreview-2559634301)

```yaml
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/1.7.2b/zen.installer.exe
  InstallerSha256: CCE695B0B94240951C236B7F2ADC6F6A874682857E802340A4B6729A3D725257
- Architecture: arm64
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/1.7.2b/zen.installer-arm64.exe
  InstallerSha256: 5F68A9A856E7471E086CCFE1F36313AFF83DCEBF1FD3483E2A6CA41DF24F2F86
```
