### ISSUE TITLE
[Bug]: wrong DisplayName of nsis installer

### ISSUE THREAD

**Issue by a-mnich** [russellbanks/Komac#1037]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

When updating/analyzing Jellyfin.Server the DisplayName is analyzed as `DisplayName: Jellyfin Server $_44_` while the package actually installs as `Jellyfin.Server 10.10.5`

[NSIS installer source code](https://github.com/jellyfin/jellyfin-server-windows/blob/master/nsis/jellyfin.nsi)

```
komac update Jellyfin.Server --version 10.10.5 --urls https://github.com/jellyfin/jellyfin-server-windows/releases/download/10.10.5/jellyfin_10.10.5_windows-x64.exe

# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Jellyfin.Server
PackageVersion: 10.10.5
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2025-01-25
AppsAndFeaturesEntries:
- DisplayName: Jellyfin Server $_44_
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Jellyfin\Server'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/jellyfin/jellyfin-server-windows/releases/download/10.10.5/jellyfin_10.10.5_windows-x64.exe
  InstallerSha256: 2AF264CB60A1A12B39B9C326D5AE3E21D49C0F255E71F428CD0E88966CAEA71F
ManifestType: installer
ManifestVersion: 1.9.0
```
