### ISSUE TITLE
[Bug]: Duplicate `AppsAndFeaturesEntries`

### ISSUE THREAD

**Issue by vikingnope** [russellbanks/Komac#1276]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Not sure if this is a bug, but for the following file: https://github.com/glzr-io/glazewm/releases/download/v3.9.0/glazewm-v3.9.0.exe, I got duplicate entries for the `AppsAndFeaturesEntries`.

```yaml
PackageIdentifier: glzr-io.glazewm
PackageVersion: 3.9.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{0F9E07AA-23F7-4975-9F97-71F0F758D5B7}'
ReleaseDate: 2025-06-13
AppsAndFeaturesEntries:
- ProductCode: '{834DD677-1584-4902-8A65-5E19EE5F23E7}'
  UpgradeCode: '{F57ADFF3-4521-4A6B-87B1-D34A7D9BAE1E}'
  InstallerType: burn
- ProductCode: '{834DD677-1584-4902-8A65-5E19EE5F23E7}'
  UpgradeCode: '{EF0F849B-D90D-4647-BB26-730C6FCE5F9E}'
  InstallerType: wix
- ProductCode: '{834DD677-1584-4902-8A65-5E19EE5F23E7}'
  UpgradeCode: '{EF0F849B-D90D-4647-BB26-730C6FCE5F9E}'
  InstallerType: wix
- DisplayName: Zebar
  DisplayVersion: 3.1.0
  ProductCode: '{834DD677-1584-4902-8A65-5E19EE5F23E7}'
  UpgradeCode: '{570D3DD8-FDBD-5B5C-A519-2FF34BA60B33}'
  InstallerType: wix
- DisplayName: Zebar
  DisplayVersion: 3.1.0
  ProductCode: '{834DD677-1584-4902-8A65-5E19EE5F23E7}'
  UpgradeCode: '{570D3DD8-FDBD-5B5C-A519-2FF34BA60B33}'
  InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/glzr-io/glazewm/releases/download/v3.9.0/glazewm-v3.9.0.exe
  InstallerSha256: D7E41913DE0F3C33A7EC7A6F32E1581C587DD2C9687708DE6883CD5D8F03A7F2
ManifestType: installer
ManifestVersion: 1.10.0
```

This leads to the following error:

```sh
Manifest Error: Schema Error. [Schema validation failed.
Error context: <root>[AppsAndFeaturesEntries] Description: Elements at indexes #1 and #2 violate uniqueness constraint.
Error context: <root>[AppsAndFeaturesEntries] Description: Elements at indexes #3 and #4 violate uniqueness constraint.
Error context: <root> Description: Failed to validate against schema associated with property name 'AppsAndFeaturesEntries'.
] File: glzr-io.glazewm.installer.yaml
Write-Error: Manifest validation failed
```
