### ISSUE TITLE
[Bug]: Sometimes not capable to create manifest with more than 2 archs

### ISSUE THREAD

**Issue by CreeperKong** [russellbanks/Komac#1288]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I have encountered an issue when I try to create manifest with more than 2 archs, which breaks automatic workflows for WinGet update. So now I temporally do manual composing of the manifests.

What weird is that this is not happening every time.

## Case 1
```
komac update --skip-pr-check --dry-run -o F:\dev\winget-pkgs BellSoft.LibericaJRE.11 --version "11.0.27+9" --urls https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-amd64.msi https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-i586.msi
```

```
komac update --skip-pr-check --dry-run -o F:\dev\winget-pkgs BellSoft.LibericaJRE.11 --version "11.0.27+9" --urls https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-amd64.msi https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-i586.msi https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
```

Get x64 and x86 without arm64, same result as the following.

```
komac update --skip-pr-check --dry-run -o F:\dev\winget-pkgs BellSoft.LibericaJRE.11 --version "11.0.27+9" --urls https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-amd64.msi https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-i586.msi
```

```YAML
PackageIdentifier: BellSoft.LibericaJRE.11
PackageVersion: 11.0.27+9
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2025-04-14
Installers:
- Architecture: x86
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-i586.msi
  InstallerSha256: 0549030A2E125982E0344857830FF02E7A264913E97D45F44DF9664DF990C085
  ProductCode: '{331205D1-7136-40B8-BF2B-070DF7D47B33}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (32-bit)
    DisplayVersion: 11.0.27.9
    ProductCode: '{331205D1-7136-40B8-BF2B-070DF7D47B33}'
    UpgradeCode: '{94F3D44C-2C45-431A-B048-363270164F62}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\BellSoft\LibericaJRE-11'
- Architecture: x64
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-amd64.msi
  InstallerSha256: C5E23D16C4DF9B156A36D61EE9199F45634B019800C3BA39B40B305AF69AAB23
  ProductCode: '{A4DC7335-21DE-428C-99E5-9372044F6505}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (64-bit)
    DisplayVersion: 11.0.27.9
    ProductCode: '{A4DC7335-21DE-428C-99E5-9372044F6505}'
    UpgradeCode: '{458EE406-2769-4CF2-B857-F971EF79E418}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\BellSoft\LibericaJRE-11'
ManifestType: installer
ManifestVersion: 1.10.0
```

## Case 2

```
komac update --skip-pr-check --dry-run -o F:\dev\winget-pkgs BellSoft.LibericaJRE.11 --version "11.0.27+9" --urls https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
```

Get only arm64 which have no issue.

```YAML
Successfully written all manifest files to F:\dev\winget-pkgs\manifests/b/BellSoft/LibericaJRE/11/11.0.27+9
# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: BellSoft.LibericaJRE.11
PackageVersion: 11.0.27+9
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: uninstallPrevious
ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
ReleaseDate: 2025-04-14
AppsAndFeaturesEntries:
- DisplayName: Liberica JRE 11 (AArch64)
  DisplayVersion: 11.0.27.9
  ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
  UpgradeCode: '{0DB467F5-36E7-4F83-AED6-1C4A7511C144}'
InstallationMetadata:
  DefaultInstallLocation: Program Files (Arm)\BellSoft\LibericaJRE-11
Installers:
- Architecture: arm64
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
  InstallerSha256: 0D20065E0654E4908E02AB3EAD78AD324D65FFB6FC847491FBF36EEAFB92D5F4
ManifestType: installer
ManifestVersion: 1.10.0
```

## Case 3

```
komac update --skip-pr-check --dry-run -o F:\dev\winget-pkgs BellSoft.LibericaJRE.11 --version "11.0.27+9" --urls https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-amd64.msi https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
```

Get x64 and arm64 which have no issue.

```YAML
PackageIdentifier: BellSoft.LibericaJRE.11
PackageVersion: 11.0.27+9
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2025-04-14
Installers:
- Architecture: x64
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-amd64.msi
  InstallerSha256: C5E23D16C4DF9B156A36D61EE9199F45634B019800C3BA39B40B305AF69AAB23
  ProductCode: '{A4DC7335-21DE-428C-99E5-9372044F6505}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (64-bit)
    DisplayVersion: 11.0.27.9
    ProductCode: '{A4DC7335-21DE-428C-99E5-9372044F6505}'
    UpgradeCode: '{458EE406-2769-4CF2-B857-F971EF79E418}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\BellSoft\LibericaJRE-11'
- Architecture: arm64
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
  InstallerSha256: 0D20065E0654E4908E02AB3EAD78AD324D65FFB6FC847491FBF36EEAFB92D5F4
  ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (AArch64)
    DisplayVersion: 11.0.27.9
    ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
    UpgradeCode: '{0DB467F5-36E7-4F83-AED6-1C4A7511C144}'
  InstallationMetadata:
    DefaultInstallLocation: Program Files (Arm)\BellSoft\LibericaJRE-11
ManifestType: installer
ManifestVersion: 1.10.0
```

## Case 4

```
komac update --skip-pr-check --dry-run -o F:\dev\winget-pkgs BellSoft.LibericaJRE.11 --version "11.0.27+9" --urls https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-i586.msi https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
```

Get x86 and arm64 which have no issue.

```YAML
PackageIdentifier: BellSoft.LibericaJRE.11
PackageVersion: 11.0.27+9
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2025-04-14
Installers:
- Architecture: x86
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-i586.msi
  InstallerSha256: 0549030A2E125982E0344857830FF02E7A264913E97D45F44DF9664DF990C085
  ProductCode: '{331205D1-7136-40B8-BF2B-070DF7D47B33}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (32-bit)
    DisplayVersion: 11.0.27.9
    ProductCode: '{331205D1-7136-40B8-BF2B-070DF7D47B33}'
    UpgradeCode: '{94F3D44C-2C45-431A-B048-363270164F62}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\BellSoft\LibericaJRE-11'
- Architecture: arm64
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
  InstallerSha256: 0D20065E0654E4908E02AB3EAD78AD324D65FFB6FC847491FBF36EEAFB92D5F4
  ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (AArch64)
    DisplayVersion: 11.0.27.9
    ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
    UpgradeCode: '{0DB467F5-36E7-4F83-AED6-1C4A7511C144}'
  InstallationMetadata:
    DefaultInstallLocation: Program Files (Arm)\BellSoft\LibericaJRE-11
ManifestType: installer
ManifestVersion: 1.10.0
```

**Comment by russellbanks** [comment]
This is because komac currently matches the URLs provided to the previous manifest and therefore doesn't automatically change the number of installer entries if this changes between versions.

Since you made https://github.com/microsoft/winget-pkgs/pull/268759 (which has three installer entries rather than two in the version prior), this now works as expected:

```yaml
PackageIdentifier: BellSoft.LibericaJRE.11
PackageVersion: 11.0.27+9
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: uninstallPrevious
ReleaseDate: 2025-04-14
Installers:
- Architecture: x86
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-i586.msi
  InstallerSha256: 0549030A2E125982E0344857830FF02E7A264913E97D45F44DF9664DF990C085
  ProductCode: '{331205D1-7136-40B8-BF2B-070DF7D47B33}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (32-bit)
    DisplayVersion: 11.0.27.9
    ProductCode: '{331205D1-7136-40B8-BF2B-070DF7D47B33}'
    UpgradeCode: '{94F3D44C-2C45-431A-B048-363270164F62}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\BellSoft\LibericaJRE-11'
- Architecture: x64
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-amd64.msi
  InstallerSha256: C5E23D16C4DF9B156A36D61EE9199F45634B019800C3BA39B40B305AF69AAB23
  ProductCode: '{A4DC7335-21DE-428C-99E5-9372044F6505}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (64-bit)
    DisplayVersion: 11.0.27.9
    ProductCode: '{A4DC7335-21DE-428C-99E5-9372044F6505}'
    UpgradeCode: '{458EE406-2769-4CF2-B857-F971EF79E418}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\BellSoft\LibericaJRE-11'
- Architecture: arm64
  InstallerUrl: https://download.bell-sw.com/java/11.0.27+9/bellsoft-jre11.0.27+9-windows-aarch64.msi
  InstallerSha256: 0D20065E0654E4908E02AB3EAD78AD324D65FFB6FC847491FBF36EEAFB92D5F4
  ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
  AppsAndFeaturesEntries:
  - DisplayName: Liberica JRE 11 (AArch64)
    DisplayVersion: 11.0.27.9
    ProductCode: '{BB69481D-3765-440A-A9D0-FDEF0D867350}'
    UpgradeCode: '{0DB467F5-36E7-4F83-AED6-1C4A7511C144}'
  InstallationMetadata:
    DefaultInstallLocation: Program Files (Arm)\BellSoft\LibericaJRE-11
```

The reason that komac works this way is because of metadata that the previous installer may have had, that komac needs to match against, and there are times where one installer URL would create two entries (one with a switch to install at machine-level and one with a switch to installer at user-level)..

Now that komac's analysis has got much more advanced and can retrieve all this information from the installer itself, I'm thinking of changing it to ignore what the previous installer entries were which would then allow the number of entries to change between versions. This was requested in #210 and I will track progress there going forward.
