### ISSUE TITLE
[Bug]: Komac incorrectly using arm64 binary for x64 architecture

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/ArmCord/ArmCord/actions/runs/4972653487/jobs/8897984711

```
Executing command: java -jar komac.jar update --id 'ArmCord.ArmCord' --version 3.2.0 --urls 'https://github.com/ArmCord/ArmCord/releases/download/v3.2.0/ArmCord.Setup.3.2.0.ARM64.exe,https://github.com/ArmCord/ArmCord/releases/download/v3.2.0/ArmCord.Setup.3.2.0.exe' --submit
  CI environment detected! Komac will throw errors instead of prompting on invalid input
  Found ArmCord.ArmCord in the winget-pkgs repository
  Found latest version: 3.1.7
  # Created with WinGet Releaser v2 using Komac v1.6.0
  # yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json
  
  PackageIdentifier: ArmCord.ArmCord
  PackageVersion: 3.2.0
  InstallerType: nullsoft
  Scope: user
  UpgradeBehavior: install
  ReleaseDate: 2023-05-[14](https://github.com/ArmCord/ArmCord/actions/runs/4972653487/jobs/8897984711#step:2:15)
  Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ArmCord/ArmCord/releases/download/v3.2.0/ArmCord.Setup.3.2.0.ARM64.exe
    InstallerSha256: 8AB84F27C7284E0FC55E549CED81DD9B8AE2EB9FD[20](https://github.com/ArmCord/ArmCord/actions/runs/4972653487/jobs/8897984711#step:2:21)4DC44614835929C7DE9DE
  - Architecture: arm64
    InstallerUrl: https://github.com/ArmCord/ArmCord/releases/download/v3.2.0/ArmCord.Setup.3.2.0.ARM64.exe
    InstallerSha[25](https://github.com/ArmCord/ArmCord/actions/runs/4972653487/jobs/8897984711#step:2:26)6: 8AB84F[27](https://github.com/ArmCord/ArmCord/actions/runs/4972653487/jobs/8897984711#step:2:28)C7[28](https://github.com/ArmCord/ArmCord/actions/runs/4972653487/jobs/8897984711#step:2:29)4E0FC55E549CED81DD9B8AE2EB9FD204DC446148359[29](https://github.com/ArmCord/ArmCord/actions/runs/4972653487/jobs/8897984711#step:2:30)C7DE9DE
  ManifestType: installer
  ManifestVersion: 1.4.0
```

The second URL doesn't get used, and the arm64 link was incorrectly provided in the x64 arch.
