### ISSUE TITLE
[Bug]: Different fields for each installer got dropped

### ISSUE THREAD

**Issue by aaronliu0130** [russellbanks/Komac#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

See [microsoft/winget-pkgs@`69c421e` (#119225)](https://github.com/microsoft/winget-pkgs/pull/119225/commits/69c421e7aa59fedc08afcc0a4715a318c8a0053d)
Komac based it on 2023.03-1 which probably also is a bug
![image](https://github.com/russellbanks/Komac/assets/11874211/3117c834-5eed-4bf5-b444-76d2da560719)
Excerpt:
```yml
- Architecture: x64
  Scope: user
  InstallerUrl: https://repo.anaconda.com/archive/Anaconda3-2023.03-1-Windows-x86_64.exe
  InstallerSha256: F13A2AE812D2069654521E7B1D897227EA4AF52BFF7CD8B3D80E7B2271FC79E4
  InstallerSwitches:
    Custom: /InstallationType=JustMe /AddToPath=1 /RegisterPython=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://repo.anaconda.com/archive/Anaconda3-2023.03-1-Windows-x86_64.exe
  InstallerSha256: F13A2AE812D2069654521E7B1D897227EA4AF52BFF7CD8B3D80E7B2271FC79E4
  InstallerSwitches:
    Custom: /InstallationType=AllUsers /AddToPath=1 /RegisterPython=1
```
and after komac updated it, it tried to unify the switches:
```yml
Scope: user
InstallerSwitches:
  Custom: /InstallationType=JustMe /AddToPath=1 /RegisterPython=0
...
Installers:
- Architecture: x64
  InstallerUrl: https://repo.anaconda.com/archive/Anaconda3-2023.07-2-Windows-x86_64.exe
  InstallerSha256: B48E103546742B2FCB77C4099660A28901476932472D16EEF6C5A63DE8B6A7CE
- Architecture: x64
  InstallerUrl: https://repo.anaconda.com/archive/Anaconda3-2023.07-2-Windows-x86_64.exe
  InstallerSha256: B48E103546742B2FCB77C4099660A28901476932472D16EEF6C5A63DE8B6A7CE
```
