### ISSUE TITLE
[Bug]: "Error making HTTP request", "error decoding response body", "invalid value"

### ISSUE THREAD

**Issue by Exorcism0666** [russellbanks/Komac#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/russellbanks/Komac/assets/46537034/fca19af2-12b8-4762-b040-8b8f290aed25)
![image](https://github.com/russellbanks/Komac/assets/46537034/838a1466-2b2d-4cc3-abb9-7bd5655c4708)

All logs: https://github.com/Exorcism0666/AutoPublish/actions/runs/7737788567/job/21097374527

**Comment by Exorcism0666** [comment]
@russellbanks this issue it's still here:
![image](https://github.com/russellbanks/Komac/assets/46537034/e64c053c-3b41-4898-9f36-98dee8aba5f8)

**Comment by russellbanks** [comment]
> @russellbanks this issue it's still here

I haven't released Komac v2.0.4 yet. Testing that command with Tutanota works on main:

```yaml
# Created with komac v2.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Tutanota.Tutanota
PackageVersion: 3.122.3
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2024-02-08
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/tutao/tutanota/releases/download/tutanota-desktop-release-3.122.3/tutanota-desktop-win.exe
  InstallerSha256: A565D0B2330DFD066366911A7253AF950B71B96DB4C9A53926DE20EC41374021
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/tutao/tutanota/releases/download/tutanota-desktop-release-3.122.3/tutanota-desktop-win.exe
  InstallerSha256: A565D0B2330DFD066366911A7253AF950B71B96DB4C9A53926DE20EC41374021
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0
```
