### ISSUE TITLE
[Bug]: Fail to detect Betterbird installer locale

### ISSUE THREAD

**Issue by hlqviet** [russellbanks/Komac#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried updating the manifest for Betterbird which has many URLs for different locales. Komac failed to detect the locale and just use the same URL.
Command
```cmd
komac update --identifier Betterbird.Betterbird --version 115.8.0-bb24 --urls https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.en-US.win64.installer.exe https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.de.win64.installer.exe https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.es-AR.win64.installer.exe https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.fr.win64.installer.exe https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.ja.win64.installer.exe https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.nl.win64.installer.exe https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.pt-BR.win64.installer.exe
```
Output
```
Latest version of Betterbird.Betterbird: 115.7.0-bb23
# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json                              
PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
  InstallLocation: /InstallDirectoryPath=<INSTALLPATH>
UpgradeBehavior: install
ReleaseDate: 2024-02-21
AppsAndFeaturesEntries:
- DisplayVersion: 115.7.0
Installers:
- InstallerLocale: de-DE
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
- InstallerLocale: en-US
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
- InstallerLocale: es-AR
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
- InstallerLocale: fr-FR
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
- InstallerLocale: it-IT
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
- InstallerLocale: ja-JP
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
- InstallerLocale: nl-NL
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
- InstallerLocale: pt-BR
  Architecture: x64
  InstallerUrl: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.8.0-bb24.it.win64.installer.exe
  InstallerSha256: 58E792ABF486BA6FB0373D029806759708C16F02D48E38453A9DEF94C8523529
ManifestType: installer
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
PackageLocale: en-US
Publisher: Betterbird Project
PublisherUrl: https://www.betterbird.eu/
PublisherSupportUrl: https://www.betterbird.eu/support/index.html
PrivacyUrl: https://www.betterbird.eu/legal/index.html
PackageName: Betterbird
License: Mozilla Public License Version 2.0
LicenseUrl: https://www.mozilla.org/MPL/2.0
CopyrightUrl: https://www.betterbird.eu/legal/index.html
ShortDescription: Betterbird is a fork of Mozilla Thunderbird with additional features and bugfixes.
Moniker: betterbird
Tags:
- e-mail
- fork
- mail
- mozilla
- thunderbird
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://betterbird.eu/faq/index.html
ManifestType: defaultLocale
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
PackageLocale: de
ShortDescription: Betterbird ist eine Variante (Fork) von Mozilla Thunderbird, der zusätzliche Features und Bugfixes enthält.
ManifestType: locale
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
PackageLocale: es-AR
ShortDescription: Betterbird es una bifurcación de Mozilla Thunderbird con funciones y correcciones de errores adicionales.
ManifestType: locale
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
PackageLocale: fr
ShortDescription: Betterbird est un fork de Mozilla Thunderbird avec des fonctionnalités et des corrections de bogues supplémentaires.
ManifestType: locale
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
PackageLocale: it
ShortDescription: Betterbird è un fork di Mozilla Thunderbird con funzioni e correzioni di bug aggiuntive.
ManifestType: locale
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
PackageLocale: nl
ShortDescription: Betterbird is een afsplitsing van Mozilla Thunderbird met extra functies en bugfixes.
ManifestType: locale
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
PackageLocale: pt-BR
ShortDescription: Betterbird é um fork do Mozilla Thunderbird com recursos e correções de bugs adicionais.
ManifestType: locale
ManifestVersion: 1.6.0

# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Betterbird.Betterbird
PackageVersion: 115.8.0-bb24
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0

> Would you like to make a pull request for Betterbird.Betterbird 115.8.0-bb24?
```

**Comment by aaronliu0130** [comment]
Also happens for me. I think maybe this should use the old behavior where komac asked you for links for every different locale.

**Comment by kjxbyz** [comment]
same issue.

**1.0.0.398**
```
# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.7-4-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Insco.PicGuard
PackageVersion: 1.0.0.398
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2024-08-23
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/picguard/picguard/releases/download/v1.0.0%2B398/picguard_1.0.0+398_windows_x64_en-US.msi
  InstallerSha256: FEE9D399F28715398A60A8EB128DC1FD8EE2F953395A7742681689B35EB6F7C0
  InstallerLocale: en-US
  ProductCode: '{BE455891-BB66-45C8-B52F-4DAB6225511C}'
  AppsAndFeaturesEntries:
  - ProductCode: '{BE455891-BB66-45C8-B52F-4DAB6225511C}'
    UpgradeCode: '{62EB3032-F9FB-4440-8DEF-B9D7BDFFD9F4}'
- Architecture: x64
  InstallerUrl: https://github.com/picguard/picguard/releases/download/v1.0.0%2B398/picguard_1.0.0+398_windows_x64_zh-CN.msi
  InstallerSha256: 89F98E8605AF63EDB8001DB615C6EA40E09D1C6968BF78007872CACEF5D38BD4
  InstallerLocale: zh-CN
  ProductCode: '{57E7F7E0-6976-4CAC-826B-83D156A5D7CE}'
  AppsAndFeaturesEntries:
  - ProductCode: '{57E7F7E0-6976-4CAC-826B-83D156A5D7CE}'
    UpgradeCode: '{62EB3032-F9FB-4440-8DEF-B9D7BDFFD9F4}'
ManifestType: installer
ManifestVersion: 1.6.0
```

**1.0.0.400**
```
# Created with komac v2.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Insco.PicGuard
PackageVersion: 1.0.0.400
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{8FAE701D-A8AA-407D-ADA4-BAE1649DBC33}'
ReleaseDate: 2024-08-25
AppsAndFeaturesEntries:
- DisplayName: PicGuard
  Publisher: INSCO LLC
  ProductCode: '{8FAE701D-A8AA-407D-ADA4-BAE1649DBC33}'
  UpgradeCode: '{62EB3032-F9FB-4440-8DEF-B9D7BDFFD9F4}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/./INSCO LLC/PicGuard/data/flutter_assets'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/picguard/picguard/releases/download/v1.0.0+400/picguard_1.0.0+400_windows_x64_en-US.msi
  InstallerSha256: 0EFA380B05834A6F3325110A4061F852D60DBA68A5016F3A558959253351A3EC
- Architecture: x64
  InstallerUrl: https://github.com/picguard/picguard/releases/download/v1.0.0+400/picguard_1.0.0+400_windows_x64_en-US.msi
  InstallerSha256: 0EFA380B05834A6F3325110A4061F852D60DBA68A5016F3A558959253351A3EC
ManifestType: installer
ManifestVersion: 1.6.0
```
