### ISSUE TITLE
[Bug]: Failed to get content length from Sourceforge urls

### ISSUE THREAD

**Issue by OfficialEsco** [russellbanks/Komac#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I keep encountering "Failed to get content length from (url)" when trying to update sourceforge packages
Tested with 3 urls that should point to the correct installer

Attempt 1
```
./KomacPortable-linux-x64 update -i mguessan.davmail -v 6.2.1-3496 -u https://sourceforge.net/projects/davmail/files/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe/download
```
```
Latest version of mguessan.davmail: 6.0.1-3390
Error: 
   0: Failed to get content length from 'https://sourceforge.net/projects/davmail/files/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe/download'
```
Attempt 2
```
❯ ./KomacPortable-linux-x64 update -i mguessan.davmail -v 6.2.1-3496 -u https://sourceforge.net/projects/davmail/files/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe
```
```
Latest version of mguessan.davmail: 6.0.1-3390
Error: 
   0: Failed to get content length from 'https://sourceforge.net/projects/davmail/files/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe'
```
Attempt 3
```
❯ ./KomacPortable-linux-x64 update -i mguessan.davmail -v 6.2.1-3496 -u https://kumisystems.dl.sourceforge.net/project/davmail/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe
```
```
Latest version of mguessan.davmail: 6.0.1-3390
Error: 
   0: Failed to get content length from 'https://kumisystems.dl.sourceforge.net/project/davmail/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe'

```

**Comment by russellbanks** [comment]
Could you possible test this with a [nightly release](https://github.com/russellbanks/Komac/releases/tag/nightly)? I can't reproduce this on main. The content length is retrieved correctly and the progress bar shows a file size of 6.56mb:

```
komac update -i mguessan.davmail -v 6.2.1-3496 -u https://sourceforge.net/projects/davmail/files/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe/download
```

```yaml
# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: mguessan.davmail
PackageVersion: 6.2.1-3496
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2024-01-04
Installers:
- Architecture: x86
  InstallerUrl: https://kumisystems.dl.sourceforge.net/project/davmail/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe
  InstallerSha256: 2E7FD10779F7582837E9A6450AAA258F92B4E4C90BB923760E62B62536DCC780
- Architecture: x64
  InstallerUrl: https://kumisystems.dl.sourceforge.net/project/davmail/davmail/6.2.1/davmail-6.2.1-3496-setup64.exe
  InstallerSha256: 2E7FD10779F7582837E9A6450AAA258F92B4E4C90BB923760E62B62536DCC780
ManifestType: installer
ManifestVersion: 1.6.0
```
