### ISSUE TITLE
[Bug]: `Komac update` does not update `RelativeFilePath` in nested installer

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```console
> Komac update -i lsd-rs.lsd -v 1.1.1 -u https://github.com/lsd-rs/lsd/releases/download/v1.1.1/lsd-v1.1.1-x86_64-pc-windows-msvc.zip https://github.com/lsd-rs/lsd/releases/download/v1.1.1/lsd-v1.1.1-i686-pc-windows-msvc.zip
...
# Created with komac v2.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: lsd-rs.lsd
PackageVersion: 1.1.1
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2024-03-23
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: lsd-v1.0.0-i686-pc-windows-msvc/lsd.exe
  InstallerUrl: https://github.com/lsd-rs/lsd/releases/download/v1.1.1/lsd-v1.1.1-i686-pc-windows-msvc.zip
  InstallerSha256: 19BE09DD4B47D8CA9B01F11897CFDDD78427C79E948B3E24B4D4407824DBA5E2
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: lsd-v1.0.0-x86_64-pc-windows-msvc/lsd.exe
  InstallerUrl: https://github.com/lsd-rs/lsd/releases/download/v1.1.1/lsd-v1.1.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: 3E9A01B8AD0B5B468175325F97547CCB05BBC5EB81E8F962336549A56F3EAD49
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.6.0
...
```

**Comment by russellbanks** [comment]
This was identified in https://github.com/russellbanks/Komac/issues/479#issuecomment-1955252830 and is fixed on main:

```yaml
# Created with komac v2.1.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: lsd-rs.lsd
PackageVersion: 1.1.1
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
ReleaseDate: 2024-03-23
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: lsd-v1.1.1-i686-pc-windows-msvc/lsd.exe
  InstallerUrl: https://github.com/lsd-rs/lsd/releases/download/v1.1.1/lsd-v1.1.1-i686-pc-windows-msvc.zip
  InstallerSha256: 19BE09DD4B47D8CA9B01F11897CFDDD78427C79E948B3E24B4D4407824DBA5E2
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: lsd-v1.1.1-x86_64-pc-windows-msvc/lsd.exe
  InstallerUrl: https://github.com/lsd-rs/lsd/releases/download/v1.1.1/lsd-v1.1.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: 3E9A01B8AD0B5B468175325F97547CCB05BBC5EB81E8F962336549A56F3EAD49
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.6.0
```
