### ISSUE TITLE
[Bug]: The value of "NestedInstallerFiles" went missing

### ISSUE THREAD

**Issue by CoolPlayLin** [russellbanks/Komac#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/microsoft/winget-pkgs/pull/149009/commits/0bfb1f6a505e582685f239c342c2af3c5e2d6fd5

In previous version, it should be 
```yaml
NestedInstallerFiles:
- RelativeFilePath: bun-windows-x64-baseline-profile\bun.exe
  PortableCommandAlias: bun
- RelativeFilePath: .\bun-windows-x64-baseline-profile\bun.exe
  PortableCommandAlias: bunx
```

But in the newest manifest generated by Komac, it went missing.
