### ISSUE TITLE
[Bug]: Komac broke Azure CLI portable installer `PortableCommandAlias` for v2.62.0 in winget-pkgs

### ISSUE THREAD

**Issue by o-l-a-v** [russellbanks/Komac#726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Like pointed out in PR <https://github.com/microsoft/winget-pkgs/pull/162494> before it got merged:

* <https://github.com/microsoft/winget-pkgs/pull/162494#issuecomment-2222433830>

Azure CLI v2.61.0 has <https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/AzureCLI/2.61.0/Microsoft.AzureCLI.installer.yaml>:

```yaml
- Architecture: x64
  InstallerUrl: https://azcliprod.blob.core.windows.net/zip/azure-cli-2.61.0-x64.zip
  InstallerSha256: 8B5F12064AAF40EECCD17C5043DF9CB5676A3845EA1BCE4ADDE33261F4AF05CD
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: bin\az.cmd
    PortableCommandAlias: az
```

Azure CLI v2.62.0 has <https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/AzureCLI/2.62.0/Microsoft.AzureCLI.installer.yaml>:

```yaml
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: python.exe
    PortableCommandAlias: az
  InstallerUrl: https://azcliprod.blob.core.windows.net/zip/azure-cli-2.62.0-x64.zip
  InstallerSha256: 204A7BA4B14A9BDD8E87639B82166634C0EA4D384E3018DF06C42226E93579CD
```

The alias `az` must be pointed to `bin\az.cmd`, not `python.exe`.
