### ISSUE TITLE
[Bug]: arm64 installers ignored and machine/user installer mismatch

### ISSUE THREAD

**Issue by a-mnich** [russellbanks/Komac#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to add the `arm64 installers` to `Microsoft.AzureDataStudio`. Somehow the arm64 instlallers were ignored and the machine/user installers got mixed up. The user installer got mapped to the user and machine installer.
```
 komac update Microsoft.AzureDataStudio --version 1.49.1 --urls https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-user-setup-1.49.1.exe https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-setup-1.49.1.exe https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-user-setup-1.49.1.exe https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-setup-1.49.1.exe
```
Result:
```
# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
                                                                                                                        PackageIdentifier: Microsoft.AzureDataStudio
PackageVersion: 1.49.1
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Commands:
- azuredatastudio
ProductCode: '{1F0FD1CE-9703-4734-8F50-5B5CEEDAE6B9}_is1'
ReleaseDate: 2024-08-14
AppsAndFeaturesEntries:
- Publisher: Microsoft Corporation
  ProductCode: '{1F0FD1CE-9703-4734-8F50-5B5CEEDAE6B9}_is1'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-user-setup-1.49.1.exe
  InstallerSha256: A9805DD11407F88810780CD03247EA31BD86E9E8CB14ED30776A704C38AD42B3
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-user-setup-1.49.1.exe
  InstallerSha256: A9805DD11407F88810780CD03247EA31BD86E9E8CB14ED30776A704C38AD42B3
ManifestType: installer
ManifestVersion: 1.6.0
```

**Comment by russellbanks** [comment]
This would be because komac tries to pair the given installers with the previous installers. As the previous manifest at the time only had 2 installers, it could only pair those two previous ones against two new ones.

There is #210 to be able to add or remove installers when using `komac update` that I will look into implementing.

Now that arm64 installers have been added, all installers are matched.

```yaml
# Created with komac v2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.AzureDataStudio
PackageVersion: 1.49.1
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /mergetasks=!runcode
UpgradeBehavior: install
Commands:
- azuredatastudio
ReleaseDate: 2024-08-14
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-user-setup-1.49.1.exe
  InstallerSha256: A9805DD11407F88810780CD03247EA31BD86E9E8CB14ED30776A704C38AD42B3
  ProductCode: '{1F0FD1CE-9703-4734-8F50-5B5CEEDAE6B9}_is1'
  AppsAndFeaturesEntries:
  - Publisher: Microsoft Corporation
    ProductCode: '{1F0FD1CE-9703-4734-8F50-5B5CEEDAE6B9}_is1'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-user-setup-1.49.1.exe
  InstallerSha256: A9805DD11407F88810780CD03247EA31BD86E9E8CB14ED30776A704C38AD42B3
  ProductCode: '{1F0FD1CE-9703-4734-8F50-5B5CEEDAE6B9}_is1'
  AppsAndFeaturesEntries:
  - Publisher: Microsoft Corporation
    ProductCode: '{1F0FD1CE-9703-4734-8F50-5B5CEEDAE6B9}_is1'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-setup-1.49.1.exe
  InstallerSha256: 2453C24036A04F644FF390E5E67F72BD583E6C22D4A4530A3F09506005C86BAD
  ProductCode: '{476E9913-B59B-492B-A75A-9C2866AFF86D}_is1'
  AppsAndFeaturesEntries:
  - Publisher: Microsoft Corporation
    ProductCode: '{476E9913-B59B-492B-A75A-9C2866AFF86D}_is1'
  ElevationRequirement: elevatesSelf
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-setup-1.49.1.exe
  InstallerSha256: 2453C24036A04F644FF390E5E67F72BD583E6C22D4A4530A3F09506005C86BAD
  ProductCode: '{476E9913-B59B-492B-A75A-9C2866AFF86D}_is1'
  AppsAndFeaturesEntries:
  - Publisher: Microsoft Corporation
    ProductCode: '{476E9913-B59B-492B-A75A-9C2866AFF86D}_is1'
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.6.0
```

You are correct though that the user and machine scope installers are mismatched; I will push a fix.
