### ISSUE TITLE
[Feature/Idea]: Update `RelativeFilePath` when updating manifest

### ISSUE THREAD

**Issue by sitiom** [russellbanks/Komac#90]
### What would you like to see changed/added?

See https://github.com/vedantmgoyal2009/winget-releaser/issues/82#issue-1558099702. Komac does not ask for a prompt for `RelativeFilePath` when updating yet.

>Support for 1.4 manifests. Also, updating the `RelativeFilePath` should be supported in cases where the executable is inside a versioned directory. For example:
>```yaml
>- RelativeFilePath: bat-v0.22.1-x86_64-pc-windows-msvc\bat.exe
>```

**Comment by russellbanks** [comment]
Are there scenarios other than versions that should be considered? Otherwise, this should already be covered - https://github.com/vedantmgoyal2009/winget-releaser/issues/82#issuecomment-1455197943.

**Comment by sitiom** [comment]
The last time I checked, it didn't work. I had to update the RelativeFilePath manually (https://github.com/microsoft/winget-pkgs/pull/97753).

**Comment by russellbanks** [comment]
I just gave it a test with your case here and it appears to work:

The important bit here is `- RelativeFilePath: fd-v8.8.0-i686-pc-windows-msvc/fd.exe`

```
[Required] Enter the Package Identifier, in the following format <Publisher shortname.Application shortname>
Example: Microsoft.Excel
Package Identifier: sharkdp.fd

Found sharkdp.fd in the winget-pkgs repository
Found latest version: 8.7.0
[Required] Enter the version.
Example: 8.44.2
Package Version: 8.8.0

Installer Entry 1/2
  Architecture: x86
  Installer Type: zip

[Required] Enter the download url to the installer
Installer Url: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-i686-pc-windows-msvc.zip

[Required] Enter the nested installer type
Options: exe, burn, inno, nullsoft, portable
Enter Choice: portable

[Optional] Enter the command line alias to be used for calling the package
Installer: fd-v8.7.0-i686-pc-windows-msvc/fd.exe
Portable Command Alias:

Installer Entry 2/2
  Architecture: x64
  Installer Type: zip

[Required] Enter the download url to the installer
Installer Url: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-i686-pc-windows-msvc.zip

# Created with Komac v1.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: sharkdp.fd
PackageVersion: 8.8.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fd-v8.8.0-i686-pc-windows-msvc/fd.exe
ReleaseDate: 2023-02-24
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-i686-pc-windows-msvc.zip
  InstallerSha256: 0C7851A9F6C587EA1ADB439748C33AF23E453EB67CB14B6F1A3B9813DB49890B
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x86
  InstallerUrl: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-i686-pc-windows-msvc.zip
  InstallerSha256: 0C7851A9F6C587EA1ADB439748C33AF23E453EB67CB14B6F1A3B9813DB49890B
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.4.0
```

**Comment by sitiom** [comment]
Here is the result when directly inputting via the parameters:
![image](https://user-images.githubusercontent.com/56180050/222992541-8eac664e-4bf3-4731-9027-de70537d65e2.png)

**Comment by russellbanks** [comment]
Ah okay, thanks for clarifying. I'll fix that now.

**Comment by russellbanks** [comment]
Fixed! :)
```
java -jar komac-1.1.0-all.jar update --id sharkdp.fd --version 8.8.0 --urls https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-i686-pc-windows-msvc.zip,https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-pc-windows-msvc.zip
Found sharkdp.fd in the winget-pkgs repository
Found latest version: 8.7.0
# Created with Komac v1.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: sharkdp.fd
PackageVersion: 8.8.0
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2023-02-24
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: fd-v8.8.0-i686-pc-windows-msvc\fd.exe
    PortableCommandAlias: fd
  InstallerUrl: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-i686-pc-windows-msvc.zip
  InstallerSha256: 0C7851A9F6C587EA1ADB439748C33AF23E453EB67CB14B6F1A3B9813DB49890B
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: fd-v8.8.0-i686-pc-windows-msvc\fd.exe
    PortableCommandAlias: fd
  InstallerUrl: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: 657CF430A1B349CE2B9CCEEAED0B14220A417BBF24A85995AA6FBF8F746F4E03
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ManifestType: installer
ManifestVersion: 1.4.0
```
