### ISSUE TITLE
[Bug]: The application panicked (crashed) when updating a specific package

### ISSUE THREAD

**Issue by myrandor** [russellbanks/Komac#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I just did a komac update of a package that changed from v19.x.x to v20.x.x and got this message.

```
Latest version of Parallels.Parallels: 19.4.25171
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src/installers/msi.rs:60
```

**Comment by russellbanks** [comment]
Hi, thanks for reporting!

This crash is fixed in the next version of komac.

Version `19.4.25171` produces the correct output:
```yaml
InstallerLocale: en-US
Architecture: x64
InstallerType: wix
InstallerSha256: D1C86916BBF5DB326BC20647D93DFE2AECB6E5DEB340C9EE34D0BE8DD4B18A17
ProductCode: '{8D22D0D5-A17B-46C5-8BBD-3F326B36A565}'
AppsAndFeaturesEntries:
- DisplayName: Parallels Client 64-bit
  Publisher: Parallels International GmbH
  DisplayVersion: 19.4.25171
  ProductCode: '{8D22D0D5-A17B-46C5-8BBD-3F326B36A565}'
  UpgradeCode: '{BC596E15-94D4-4513-A475-C218664792D5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Parallels\Client'
```

Version `20.0.25389` does actually have garbled data after being parsed by [`rust-msi`](https://github.com/mdsteele/rust-msi) so this will be the same issue as #488, which is waiting on https://github.com/mdsteele/rust-msi/pull/18.
