### ISSUE TITLE
[Bug]: InstallerSwitches at wrong level in installer.yaml?

### ISSUE THREAD

**Issue by maphew** [russellbanks/Komac#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I used komac v2.8.0 (installed with winget) to generate a new manifest interactively and create a PR at the end. All that worked, but the installer.yaml failed in Azure Pipleine validation. After some trial and error I determined that moving `InstallerSwitches` inside `Installer` blocks made the validator happy.

 * Initial komac-only yamls - https://github.com/microsoft/winget-pkgs/pull/198907/commits/28fbc25817f80731b62b4b4ab69d7af70216cc4f
 ```
...
PackageIdentifier: Tr...
PackageVersion: 0....
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
UpgradeBehavior: install
...
```
 * Failed validation - https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=36354&view=results, "

 * hand edited yaml - https://github.com/maphew/winget-pkgs/commit/4d394ca1b3d2cf402fad53ec4fe8c3e5db38699e
```
...
Installers:
- Architecture: x64
  InstallerUrl: https://github....
  InstallerSha256: 10193...
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
...
```
 * Successful validation - https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=36374&view=results

I've only made a couple of winget package manifests so the initial mistake may have been mine somehow. Now it's documented though so someone else can spend less time than me troubleshooting. ; -)

Portion of failed validation message:

> Description: Failed to validate against schema associated with property name 'Installers'. ] 
> File: TriliumNext.Notes.installer.yaml 
> Manifest Error: Encountered unexpected root node. 
> Manifest Error: Encountered unexpected root node. 
> Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
> Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.

**Comment by russellbanks** [comment]
Thanks @maphew for using komac and creating this issue! The issue here is two separate bugs:

1. The installer switch prompts should have been required not optional:

If an installer is not a known installer type (Inno, Nullsoft, WiX, etc), it is an `exe` installer type, and WinGet requires both `Silent` and `SilentWithProgress` switches for it. komac prompts for this, but the prompts were mistakenly optional so they could just be skipped by pressing enter. In the original commit, it appears only the silent switch was inputted. That's not your fault; komac isn't supposed to create invalid manifests.

2. The installer switch keys were empty at the 'installer' level:

There are two levels where keys can be placed in a manifest, the 'root' level and the 'installer' level:

Root level:
```yaml
...
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
...
```

Installer level:
```yaml
...
- Architecture: x64
  InstallerUrl: https://github....
  InstallerSha256: 10193...
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
...
```

If a specific key under an installer is the same across all installers, it's preferable for it to be placed at the root, to reduce redundancy. komac does this, but for the installer switches specifically, it wasn't removing the key if there are no switches left at the installer level, meaning it left just an empty object `{}`.

To add to this, if a key is present at both the root level and the installer level, WinGet prioritises the key at the installer level so even though the key at the root level was valid, WinGet was just looking at the empty objects at the installer level.


I'll be making two commits to resolve this :) Thank you again!
