### ISSUE TITLE
[Bug]: Duplicate x86 installers with arm installer ignored

### ISSUE THREAD

**Issue by UnownPlain** [russellbanks/Komac#965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I used Komac to update a package with x86 and arm installer with the following command:

 `komac update Zen-Team.Zen-Browser --version 1.0.2-b.2 --urls https://github.com/zen-browser/desktop/releases/download/1.0.2-b.2/zen.installer-arm64.exe https://github.com/zen-browser/desktop/releases/download/1.0.2-b.2/zen.installer-generic.exe`

Duplicate x86 installers were added with the arm installer being ignored.

```yaml
ReleaseDate: 2024-12-15
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/1.0.2-b.2/zen.installer-generic.exe
  InstallerSha256: E30A39666A4711E49822F090AD93165450B5699BA0E23F0EA7EE329C01AF77BC
- Architecture: x86
  InstallerUrl: https://github.com/zen-browser/desktop/releases/download/1.0.2-b.2/zen.installer-generic.exe
  InstallerSha256: E30A39666A4711E49822F090AD93165450B5699BA0E23F0EA7EE329C01AF77BC
ManifestType: installer
ManifestVersion: 1.9.0
```
