### ISSUE TITLE
[Bug]: wrong architecture detected

### ISSUE THREAD

**Issue by a-mnich** [russellbanks/Komac#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Something seems to have changed with the architecture detection. Multiple applications which I already updated a few times now detect a different (wrong) architecture.

```
komac update KeeperSecurity.Commander --version 16.11.20 --urls https://github.com/Keeper-Security/Commander/releases/download/v16.11.20/keeper-commander-windows-v16.11.20.exe
```
InstallerType: `inno`
Detected: `x86` Correct: `x64`
![image](https://github.com/user-attachments/assets/3c8b3fc5-3fc5-4331-9fa0-6920a258fd0d)

```
komac update wire.wire --version 3.37.5077 --urls  https://github.com/wireapp/wire-desktop/releases/download/windows/3.37.5077/Wire-Setup.exe
```
InstallerType: `exe`
Detected: `x86` Correct: `x64`
![image](https://github.com/user-attachments/assets/38610c4a-5b9c-44ce-891d-51e94ea4ce69)

```
komac update UltimateGadgetLaboratories.UHKAgent --version 5.0.0 --urls https://github.com/UltimateHackingKeyboard/agent/releases/download/v5.0.0/UHK.Agent-5.0.0-win-ia32.exe https://github.com/UltimateHackingKeyboard/agent/releases/download/v5.0.0/UHK.Agent-5.0.0-win.exe https://github.com/UltimateHackingKeyboard/agent/releases/download/v5.0.0/UHK.Agent-5.0.0-win-x64.exe
```
InstallerType: `nullsoft`
Multiple installer blocks with architecture `x86`  while the one with `UHK.Agent-5.0.0-win.exe` should be `neutral`
https://github.com/microsoft/winget-pkgs/pull/199079/commits/3e19c7d11e86e53ae03d78194d0c0a6c47bc39a1
![image](https://github.com/user-attachments/assets/1b5686a4-0429-4339-96c1-8462d10658a9)

**Comment by russellbanks** [comment]
For `KeeperSecurity.Commander`, I don't believe x64 is the correct architecture. The header of the Inno data defines it as being `x86compatible`:

```rust
architectures_allowed: ArchitectureIdentifiers(X86_COMPATIBLE),
architectures_disallowed: ArchitectureIdentifiers(0x0),
architectures_install_in_64_bit_mode: ArchitectureIdentifiers(X86_COMPATIBLE),
```

In the Inno setup [documentation](https://jrsoftware.org/ishelp/index.php?topic=archidentifiers):
> x86compatible
    Matches systems capable of running 32-bit x86 binaries. This includes systems running x86 Windows, x64 Windows, and also Arm64 Windows 10 and 11 systems, which have the ability to run x86 binaries via emulation.


x86 binaries can still install fine on x64 systems. Specifying x64 in the manifest will unnecessarily prevent users on x86 systems being unable to install it through WinGet.

**Comment by a-mnich** [comment]
> For `KeeperSecurity.Commander`, I don't believe x64 is the correct architecture. The header of the Inno data defines it as being `x86compatible`:
> 
> ```rust
> architectures_allowed: ArchitectureIdentifiers(X86_COMPATIBLE),
> architectures_disallowed: ArchitectureIdentifiers(0x0),
> architectures_install_in_64_bit_mode: ArchitectureIdentifiers(X86_COMPATIBLE),
> ```

That's interesting. When initially opening the PR with `x86`, the validation pipeline got a `validation executable error` label and with the error  `The specified executable is not a valid application for this OS platform` in the logs.  
References:
- [Logs](https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=35454&view=artifacts&pathAsName=false&type=publishedArtifacts )
- [Failed run](https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=35454&view=results)
-  [All runs of the PR](https://dev.azure.com/shine-oss/winget-pkgs/_build?definitionId=14&branchFilter=24068%2C24068%2C24068)

So in this case I would say it's an issue of the installer being declared as `x86compatible` even though it seemingly isn't. (Unfortunately I don't have a x86 machine at hand for testing this)


> The `UHK.Agent-5.0.0-win.exe` for `UltimateGadgetLaboratories.UHKAgent` is not actually a neutral installer. Neutral is a value generally used for MSIX installers that defines that it can install on `x86`, `x64`, `arm`, and `arm64` systems. This binary is instead a combination of both the x64 and x86 installers.

Thanks for checking this. Makes sense :)  
Do you happen to have any tools available for such situations? I feel a bit guilty for raising an issue since these two seem to be installer problems or just incorrect manifests.

**Comment by russellbanks** [comment]
> That's interesting. When initially opening the PR with `x86`, the validation pipeline got a `validation executable error` label and with the error `The specified executable is not a valid application for this OS platform` in the logs.

Even if a pull request gets the tag `validation executable error`, it doesn't necessarily mean there's anything wrong with the manifest. Unless it's very explicit like the manifest is clearly wrong, it's often best to see what a mod says rather than trying to make changes. For example, the pipelines could just have an issue running it and oftentimes I, as a moderator, manually rerun it and it'll be successful that time.

I tried resubmitting the pull request with the x86 architecture and while it did get the same label, this was able to be removed by another moderator - https://github.com/microsoft/winget-pkgs/pull/199434.

> I feel a bit guilty for raising an issue since these two seem to be installer problems or just incorrect manifests.

Don't feel guilty at all. Every issue I've had has been helpful to me. Even if it's not necessarily something to be fixed, it allows me to test komac on installers I haven't come across in more depth.

Also, the `wire.wire` installer is an unknown installer but I think I've found a way to be able to unpack it and get the correct architecture.

**Comment by russellbanks** [comment]
> Do you happen to have any tools available for such situations?

The next version of komac is, as always, a bit better with manifests than the previous/current version. Submitting `UltimateGadgetLaboratories.UHKAgent` with just the `x64` and `x86` URLs passed creates a more correct manifest here - https://github.com/microsoft/winget-pkgs/pull/199483.

This will be because it will try to pair up one of the installers with the 'neutral' installer, notice that it's not actually neutral and change it to x86, and then remove it because it's then identical to the x86 installer.

**Comment by hovancik** [comment]
Hi, I think I have the same issue: https://github.com/microsoft/winget-pkgs/pull/204638 

Is there some way to workaround it with kamac or should I manually change architecture in PR? 

I am asking because I would like to make this automatic via github actions when I make new release. 

Thanks!

**Comment by russellbanks** [comment]
Hi @hovancik! Thanks for reporting! This is fixed in https://github.com/russellbanks/Komac/commit/320c288462f5173c3ee92517f87a615db1257fd0 and will be included in komac v2.9.0.

**Comment by a-mnich** [comment]
Hi @russellbanks,
I've noticesd that the arm64 version of curl.curl is identified as `neutral`.
Looking back at the winget-pkgs history it seems like this change was introduced somewhen around the upgrade from komac version `2.6.0` to version `2.8.0`.
```
komac update cURL.cURL --version 8.12.0.1 --urls https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win32-mingw.zip https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win64-mingw.zip https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win64a-mingw.zip
```
```
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: curl-8.12.0_1-win32-mingw/bin/curl.exe
  InstallerUrl: https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win32-mingw.zip
  InstallerSha256: B37E3407C05A8EA30632C14AF71DB1269BC964162167EB8025DC5AE416559CAC
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: curl-8.12.0_1-win64-mingw/bin/curl.exe
  InstallerUrl: https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win64-mingw.zip
  InstallerSha256: 030F8BD879E800FFD0C3C88506766DA24EB2DF64C574AA386EF92F7E1874C458
- Architecture: neutral
  NestedInstallerFiles:
  - RelativeFilePath: curl-8.12.0_1-win64a-mingw/bin/curl.exe
  InstallerUrl: https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win64a-mingw.zip
  InstallerSha256: DD7CDC8EFC2E699CF25C9523D7BFB4E4A6141CED6C023993F1A4532369AB25B0
ManifestType: installer
ManifestVersion: 1.9.0
```
https://curl.se/windows/

**Comment by russellbanks** [comment]
> Hi [@russellbanks](https://github.com/russellbanks), I've noticesd that the arm64 version of curl.curl is identified as `neutral`. Looking back at the winget-pkgs history it seems like this change was introduced somewhen around the upgrade from komac version `2.6.0` to version `2.8.0`.

This appears to be fixed on main. `komac analyse` identifies the win64a file as arm64 and the `komac update` output is correct:
```yaml
Installers:
- Architecture: x86
  NestedInstallerFiles:
  - RelativeFilePath: curl-8.12.0_1-win32-mingw/bin/curl.exe
  InstallerUrl: https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win32-mingw.zip
  InstallerSha256: B37E3407C05A8EA30632C14AF71DB1269BC964162167EB8025DC5AE416559CAC
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: curl-8.12.0_1-win64-mingw/bin/curl.exe
  InstallerUrl: https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win64-mingw.zip
  InstallerSha256: 030F8BD879E800FFD0C3C88506766DA24EB2DF64C574AA386EF92F7E1874C458
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: curl-8.12.0_1-win64a-mingw/bin/curl.exe
  InstallerUrl: https://curl.se/windows/dl-8.12.0_1/curl-8.12.0_1-win64a-mingw.zip
  InstallerSha256: DD7CDC8EFC2E699CF25C9523D7BFB4E4A6141CED6C023993F1A4532369AB25B0
ManifestType: installer
ManifestVersion: 1.9.0
```

For good measure and because I haven't seen `win64a` used before, I'll add that as an architecture to look for in URLs (architecture is retrieved either from the URL or the file).
