### ISSUE TITLE
[Bug]: Scope is removed when updating Google.Chrome

### ISSUE THREAD

**Issue by vedantmgoyal2009** [russellbanks/Komac#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Yep I've actually already got it installed and I used it recently to update the Google.Chrome manifest. I did notice that it didn't keep the scope values when updating so I had to do that by hand. I was actually planning on making an issue or letting Russell know directly but I've been busy with a new job lol

_Reported by @warshanks to me in personal chat_

**Comment by russellbanks** [comment]
I've had a look into this and I fixed a few things surrounding this in https://github.com/russellbanks/Komac/commit/82f22451ce4cdf4f5f27714fcaa6a3ec4d178836 but when it's ran now, the scope is returned as machine. I believe this is intended behaviour. Take the installers in the installer manifest currently:

```yaml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: 0296873AAA22678387DA46AFAF1F24964A02AA15113F13BA07710507930AE966
  ProductCode: '{DA656F67-BC08-3A6B-AB08-77B40F7B6775}'
- Architecture: x86
  Scope: machine
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: 0296873AAA22678387DA46AFAF1F24964A02AA15113F13BA07710507930AE966
  ProductCode: '{DA656F67-BC08-3A6B-AB08-77B40F7B6775}'
- Architecture: x64
  Scope: user
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 370E82D3A92C89AA9151A9A756AFC683DDE2AC1E168059BBDBFCF62F2F149EC4
  ProductCode: '{17075A6A-91DC-3207-8443-B245FD58916E}'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 370E82D3A92C89AA9151A9A756AFC683DDE2AC1E168059BBDBFCF62F2F149EC4
  ProductCode: '{17075A6A-91DC-3207-8443-B245FD58916E}'
```

The user scope on here is actually incorrect as the MSI database has an `AllUsers` value of 1:
> An ALLUSERS property value of 1 specifies the per-machine installation context.

Komac priorities this as this is what is inside the MSI database.

If this really should be the intended output (I can't see why), then I could prioritise what is the previous installer, but I've avoided doing this as manifests often have incorrect data and it makes sense for Komac to "automatically" fix them as they're updated.
